[package]
name = "titan-kg986"
version = "0.1.0"
edition = "2024"
description = "Unofficial lighting control for the MARVO Titan KG986 keyboard on Linux"
license = "MIT"
authors = ["ozzenerol"]

[dependencies]
eframe = "0.36.2"
libc = "0.2.190"
png = "0.18.1"

[profile.release]
strip = true
lto = true
